### PR TITLE
Runoff BMI: fixes, adjustments for NextGen and examples

### PR DESCRIPTION
**Pull request by adlzanchetta**
Additions:
- compiling via CMake now generates a dynamic library with all the Raven functions;
- function ```CRavenBMI::GetValuePtr()``` implemented (required by NextGen);
- added two external C linkage functions (required by NextGen):
  - ```bmi_model_create()```, 
  - ```bmi_model_destroy(CRavenBMI *ptr)```;
- added boolean flag ```in_bmi_mode``` into ```optStruct``` that allows running Raven:
  - without predetermined ```EndDate``` or ```duration```;
  - without ```.rvt``` files;
  - using non-gauged, non-gridded forcings.
- configuration for ```CRavenBMI::Initialize``` now must be in ```yaml``` format (two formats supported);
- added one example (Alouette5) for running Raven in standalone and as a NextGen component.

Bugfixes:
- function ```CRavenBMI::GetVarType()``` now returns ```"double"``` (before: ```"float"```);
- function ```CRavenBMI::Finalize()``` now cleans up memory without terminating the whole program;

### CODE REVIEW

**Review by analytophile — CHANGES_REQUESTED** [review]
1)	I’d prefer to not clutter up the github with example setups at this point, and keep it only to the source code. Perhaps if we could move this to a separate git project to track. Otherwise we run the risk of having examples not following suit with the version. 

2)	The CMakeLists.txt needs to have some kind of if statement in here – if you update the global CMakeLists, is it automatically creating both the executable and the bmi library? Or is it creating the library instead  of the .exe? Ideally (I think), the CMakeLists.txt should be for the .exe with either a separate CMake file for the library or an if clause in the header which defaults to .exe only.

3)	I think there are many scenarios in which you might want to supply an .rvt in BMI mode – perhaps this can be set as a warning in ParseTimeSeriesFile.cpp rather than shutting down? The checks for a blank .rvt filename in UpdateForcings.cpp aren’t ideal – can you create a Boolean at the top of the file:

bool forcings_from_BMI=(!stcmp(Options.rvt_filename.c_str(),””)); 

as a stopgap, then use this in the rest of UpdateForcings? (it also reduces the number of calls to a string compare function, which are expensive)

4)	The rest of the code updates work well for me, and I will merge as soon as the above issues are addressed.

**Comment by adlzanchetta** [comment]
1. Sure. I removed from the repository and moved to another private repository that I have for a script that automates the comparison between the standalone Raven and the Raven BMI outputs.

2. In the first commit, running ```cmake``` and ```make``` would always produce both the ```.exe``` and the ```.so``` files. Now I added two optional arguments that act as flags to allow the user to decide if the compiling of the ```.exe``` should be suppressed (default: will compile) and if the compiling of the ```.so``` will also happen (default: suppressed).

3. 1. The way it was and it is does not inhibits BMI runs with ```.rvt``` files provided, but only shows warning messages. In ```ParseInput.cpp```, lines 1868 to 1870:
```
    if (Options.in_bmi_mode) {
        WriteWarning("ParseMainInputFile: a value was provided for .rvt files. Any set through the BMI interface will be ignored.", Options.noisy);
     }
```

Is there any part of the code that you see it shutting down if in BMI and with a ```.rvt``` file is provided?

3. 2. Indeed, recurrent string comparisons are not optimal in terms of performance. I added the suggested changes, but I named the flag ```rvt_file_provided``` rather than ```forcings_from_BMI``` just to make it more generic and mnemonic (if in the future it is decided to include another source of forcing other than BMI, this flag will still make sense to be used).

**Review by analytophile — APPROVED** [review]

**Review by analytophile — APPROVED** [review]
only minor comment - a warning should be thrown in the return(true) clause in ParseTimeSeriesFile.cpp; there are future implementations of BMI that could potentially need .rvt data, so it is useful to know when/why the code is ignoring rvt content

**Comment by analytophile** [comment]
never mind on my minor comment - no need to throw a warning. I misread.

**Pull request merged**
